FROM ghcr.io/downunderctf/docker-vendor/nsjail:ubuntu-21.04

COPY ./challenge/nsjail.cfg /home/ctf/nsjail.cfg
COPY ./challenge/flag.txt /home/ctf/chal/flag.txt
COPY ./challenge/shell /home/ctf/chal/pwn
